---
resources:
- name: repo
  type: git
  source:
    uri: git@github.com:hexly/naativ-teacher-lounge.git
    branch: Cypress
    private_key: ((git-private-key))

jobs:
- name: something-plz
  plan:
  - get: repo
  - task: running test sh file
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: node}
      inputs:
      - name: repo
      run:
        path: sh
        args: [repo/tests/concourse/test.sh]